lint:
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/sendmail_template.txt
    - assets/multiqc_config.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Niklas Schandry
  description: Assemble genomes from long ONT or pacbio HiFi reads
  force: false
  is_nfcore: true
  name: genomeassembler
  org: nf-core
  outdir: .
  skip_features:
    - multiqc
    - igenomes
  version: 2.0.0dev
