name: report
description: Create report for nf-core/genomeassembler
keywords:
  - report
  - quarto
tools:
  - quarto:
      description: An open-source scientific and technical publishing system.
      homepage: https://quarto.org/
      documentation: https://quarto.org/docs/reference/
      tool_dev_url: https://github.com/quarto-dev/quarto-cli
      licence: ["MIT"]
      identifier: ""
input:
  - qmdir_files:
      type: path
      description: |
        qmd for reporting
  - funct_files:
      type: path
      description: |
        Functions for reporting
  - script_files:
      type: path
      description: |
        Scripts for reporting
  - fastplong_files:
      type: path
      description: |
        Fastplong json outputs
  - jelly_files:
      type: path
      description: |
        Genomescope outputs
  - quast_files:
      type: path
      description: |
        quast tsv report
  - busco_files:
      type: path
      description: |
        busco short summary
  - meryl_files:
      type: path
      description: |
        merqury plot.log.png files.
  - versions:
      type: val
      description: |
        Collected versions.
  - groups:
      type: val
      description: |
        Sample - group relationshipts
output:
  - report_html:
      - - "report.html":
            type: path
            description: |
              Report html file
        - "report_files/*":
            type: path
            description: |
              Files required to view html report.
  - busco_table:
      - - "reports.csv":
            type: path
            description: |
              Collated busco reports
  - quast_table:
      - - "reports.csv":
            type: path
            description: |
              Collated quast reports
authors:
  - "@nschan"
maintainers:
  - "@nschan"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/quarto_r-gt_r-plotly_r-quarto_pruned:63d3feee82a6dacb
      build_id: bd-63d3feee82a6dacb_1
      scan_id: sc-c79312501c9678f0_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/quarto_r-gt_r-plotly_r-quarto_pruned:c2f061c1b9a368cf
      build_id: bd-c2f061c1b9a368cf_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/c6/c6aa8aa5d530d24a524eafb047d71939e1b3412edb08a92832c4fd8ab43852fb/data
  conda:
    linux/amd64:
      lock_file: modules/local/report/.conda-lock/linux_amd64-bd-63d3feee82a6dacb_1.txt
