name: report
description: Create report for nf-core/genomeassembler
keywords:
  - report
  - quarto
tools:
  - quarto:
      description: An open-source scientific and technical publishing system.
      homepage: https://quarto.org/
      documentation: https://quarto.org/docs/reference/
      tool_dev_url: https://github.com/quarto-dev/quarto-cli
      licence: ["MIT"]
      identifier: ""
input:
  - qmdir_files:
      type: path
      description: |
        qmd for reporting
  - funct_files:
      type: path
      description: |
        Functions for reporting
  - script_files:
      type: path
      description: |
        Scripts for reporting
  - fastplong_files:
      type: path
      description: |
        Fastplong json outputs
  - jelly_files:
      type: path
      description: |
        Genomescope outputs
  - quast_files:
      type: path
      description: |
        quast tsv report
  - busco_files:
      type: path
      description: |
        busco short summary
  - meryl_files:
      type: path
      description: |
        merqury plot.log.png files.
  - versions:
      type: val
      description: |
        Collected versions.
  - groups:
      type: val
      description: |
        Sample - group relationshipts
output:
  - report_html:
      - - "report.html":
            type: path
            description: |
              Report html file.
  - busco_table:
      - - "reports.csv":
            type: path
            description: |
              Collated busco reports.
  - quast_table:
      - - "reports.csv":
            type: path
            description: |
              Collated quast reports.
authors:
  - "@nschan"
maintainers:
  - "@nschan"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/ca-certificates_quarto_r-gt_r-plotly_pruned:833048f01b6491fc
      build_id: bd-833048f01b6491fc_1
      scan_id: sc-572bc0796aa5f4b2_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/ca-certificates_quarto_r-gt_r-plotly_pruned:84ed7c801a255319
      build_id: bd-84ed7c801a255319_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/62/62cee220a91255a09aa10b25f920b6b68febe137c7ed00b527d5891a3e5c7842/data
  conda:
    linux/amd64:
      lock_file: modules/local/report/.conda-lock/linux_amd64-bd-833048f01b6491fc_1.txt
