name: ragtag_scaffold
description: |
  Scaffolding is the process of ordering and orienting draft assembly (query)
  sequences into longer sequences. Gaps (stretches of "N" characters) are placed
  between adjacent query sequences to indicate the presence of unknown sequence.
  RagTag uses whole-genome alignments to a reference assembly to scaffold query sequences.
  RagTag does not alter input query sequence in any way and only orders and orients sequences, joining them with gaps.
keywords:
  - scaffolding
  - ragtag
tools:
  - RagTag:
      description: |
        RagTag is a collection of software tools for scaffolding and improving modern genome assemblies. Tasks include:
        Homology-based misassembly correction
        Homology-based assembly scaffolding and patching
        Scaffold merging
      homepage: https://github.com/malonge/RagTag
      documentation: https://github.com/malonge/RagTag/wiki
      doi: 10.1186/s13059-022-02823-7
      licence: ["MIT"]
      identifier: biotools:ragtag
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - assembly:
        type: file
        description: Assembly to be scaffolded
        pattern: "*.{fastq,fastq.gz}"
    - reference:
        type: file
        description: Reference assembly
        pattern: "*.fastq"
output:
  - corrected_assembly:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - "*.fasta":
          type: file
          description: FASTA file containing the patched assembly
          pattern: "*.fasta"
  - corrected_agp:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - "*.agp":
          type: file
          description: agp file defining how corrected_assembly is built
          pattern: "*.agp"
  - corrected_stats:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - "*.stats":
          type: file
          description: Statistics on the scaffold
          pattern: "*.stats"

  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@nschan"
maintainers:
  - "@nschan"
